### ISSUE TITLE
cannot compile on Mac

### ISSUE THREAD

**Issue by chikashimiyama** [pd-externals/vbap#3]
I just cloned this repo and execute make on my mac book pro (16-inch 2019 / Catalina).

~~~
cc -I"/Applications/Pd-extended.app/Contents/Resources/include/pd" -DPD -DVERSION='"1.1"' -arch i386 -arch x86_64 -mmacosx-version-min=10.5 -fPIC -I/sw/include -Wall -W -g -ftree-vectorize -ftree-vectorizer-verbose=2 -fast -o "vbap.o" -c "vbap.c"
clang: error: unknown argument: '-ftree-vectorizer-verbose=2'
make: *** [vbap.o] Error 1
~~~

I'm not sure if this is relevant but this makefile refers to pd-extended which is probably obsolete.

https://github.com/pd-externals/vbap/blob/master/Makefile

**Comment by danomatika** [comment]
Use the `update/1.2.0` branch.
