### ISSUE TITLE
Tried compiling this but some errors

### ISSUE THREAD

**Issue by muziker** [pd-externals/vbap#4]
So, i managed to compile this but while running through the tutorials, it seems like there's a matrix, mtx  object requirement. I assume this refers to the iemmatrix pure data, but that project is probably not 0.52 safe. Are there any other libraries that can function as drop-in replacements?

**Comment by umlaeute** [comment]
> but that project [note: iemmatrix] is probably not 0.52 safe

why do you think so?
and if it was: why do you report it here and not at the iemmatrix bug tracker?

> Are there any other libraries that can function as drop-in replacements?

for iemmatrix? as *drop-in* replacement? no.

---

what is this bug report about?

the title says "*tried compiling this but some errors*" which hints that you "got errors when trying to compile".
but the text says "*i managed to compile*" so it seems the errors where not actual "errors" (as that would have stopped compilation).

i'm closing this as it doesn't seem to be actionable upon

**Comment by danomatika** [comment]
Use the develop branch or, I’m not sure, a newer version branch. You are most likely referring to some example subpatches from the pd-extended era in the current main branch which have been updated in the development branches. We just haven’t finished merging yet.

No externals are required beyond those built via make.

**Comment by danomatika** [comment]
I've merged the update branch into master, so version 1.2.0 is current now.

**Comment by muziker** [comment]
Thanks ! Yes that's right, the examples weren't up to date, so a little confusion there. Everything compiles but the help files weren't working. There's also a bunch of else/matrix type externals that might work as replacements for the matrix operations, though i guess iemmatrix should be fine if it's supposed to be ok for 0.52

**Comment by danomatika** [comment]
> Everything compiles but the help files weren't working.

Is the current master fine now or are there still issues? If so, which help files? Also, what do you mean by "weren't working," do you mean they don't open at all or they just show load errors for missing objects?

**Comment by muziker** [comment]
IIRC the help files depend on objects that were missing.

**Comment by danomatika** [comment]
Which objects?

**Comment by danomatika** [comment]
…and which help files?

**Comment by umlaeute** [comment]
`rvbap-help.pd` still uses `[mtx]` and `[mtx_*~]` from iemmatrix, and `[import]`.

i guess the use of `[import]` can be replaced by `[declare]`.

otherwise, i don't think there's anything inherently wrong with using `iemmatrix` in the help-files.

@muziker it would be great if you could tell us what the actual problem is you are experiencing.
so far, this bug report as been mostly cryptic.

**Comment by danomatika** [comment]
I believe I removed the ie matrix usage in the other object help files and forgot this one. I should have left mention of their usage though. There is also usage of externals in some of the further example patches, but I figure that was fine.
