### ISSUE TITLE
rvbap blows up pd and outputs 'nan'

### ISSUE THREAD

**Issue by porres** [pd-externals/vbap#5]
I'm on mac mojave, and this is true in pd extended, vanilla with the download from deken and a compilation from this repository.

It keeps outputting 'nans' and then pd crashes

**Comment by umlaeute** [comment]
could you be a bit more specific on how to trigger the bug?

**Comment by porres** [comment]
for me it triggers all the time. Set the speakers, try to change any parameter (azimuth, elevation, spread, distance) and... BOOOM, Pd crash!

**Comment by danomatika** [comment]
Aside: Any particular reason to use [rvbap] instead of [vbap]? I honestly don't know what the difference between the two are. What I do know is [vbap] is used extensively in a project at my work at performs well.

**Comment by porres** [comment]
I'm not really using rvbap, just testing it. All I know is what the help says. It's supposed to work with reverbs and you can set a "distance". Will check throughly... working on externals of my own now as I mentioned in the pd list

**Comment by porres** [comment]
testing with https://github.com/pd-externals/vbap/commit/a3ac5a94d3b7341fff3b08e97864e0c5972c5daf and now I don't seem to be getting any output at all...

**Comment by porres** [comment]
while we're at it, vbap hel says 'You can also use \[vbap\] to control: cyclone/matrix~', but no example is given, and I dont see how...

I guess we can update this object in deken with the current fixes and I can also try and make a better help file... it's very old and uses third party externals, and even [import]... (in rvbap)

we should provide a main pure vanilla example in the help file and then some extra example files with third party externals... just so it doesnt look like this is still a pd extended help file

**Comment by danomatika** [comment]
Check if there is a develop branch first. I did some updates a few years ago but I don't remember if everything was merged. OTOH I think only edited vbap.

**Comment by porres** [comment]
> Check if there is a develop branch first. 

other than this? I bet not! Been looking around and as I see it, Ville Pulkki wrote some VBAP calculation code and used it to make a Max external and then Hans ported it to Pd, shiped it in Pd extended and that was it... and then it ended up here and had some more edits.

**Comment by danomatika** [comment]
The develop branch was one I made a few years ago. I just didn't remember it I merged it and wasn't near my laptop to check.

**Comment by porres** [comment]
ok, so it's merged :)

**Comment by porres** [comment]
> testing with https://github.com/pd-externals/vbap/commit/a3ac5a94d3b7341fff3b08e97864e0c5972c5daf and now I don't seem to be getting any output at all...

last commit did fix this thanks
